# Generated by Django 3.2 on 2022-08-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_featuresbyproduct_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
